- name: Check if kubens in the correct version is installed
  shell: |
    if [ "$(kubens --version)" != "{{ kubens_version }}" ]; then
      echo status=changed
    fi
  register: task
  changed_when: "'status=changed' in task.stdout"
  notify:
    - "{{ role_name }} : Download archive to tmp"
    - "{{ role_name }} : Create temporary dir for unpacked archive"
    - "{{ role_name }} : Unarchive archive to temporary dir"
    - "{{ role_name }} : Copy file with owner and permissions"
    - "{{ role_name }} : Download bash completion script and place it"
